/**
 * Signal Timing Intelligence — Scoring & Reboot Detection
 *
 * Consumes calibrated sleep timers from reports/sleep_timers.json
 * to compute signal lead scores with timing-aware probability curves.
 *
 * Integration points:
 *   - Signal feed: replace generic timestamps with timing phase + score
 *   - Signal processing pipeline: detect reboots when new signals appear
 *   - Lead scoring: composite score for outreach prioritisation
 */

const path = require('path');
const fs = require('fs');

// Load calibrated sleep timers (generated by scripts/calibrate_signal_timing.js)
let SLEEP_TIMERS = {};
const timersPath = path.join(__dirname, '..', 'reports', 'sleep_timers.json');
try {
  if (fs.existsSync(timersPath)) {
    SLEEP_TIMERS = JSON.parse(fs.readFileSync(timersPath, 'utf8'));
  }
} catch (e) {
  console.warn('signal_timing: sleep_timers.json not found — run calibrate_signal_timing.js first');
}

// Fallback timers for signal types without calibration data (conservative defaults)
const DEFAULT_TIMER = {
  dormant_until_days: 14,
  rising_from_days: 45,
  peak_start_days: 90,
  peak_end_days: 270,
  declining_until_days: 450,
  dormant_after_days: 540
};

/**
 * Compute signal lead score based on calibrated timing model.
 *
 * @param {string} signalType - e.g. 'capital_raising', 'leadership_change'
 * @param {number} signalAgeDays - days since signal was detected
 * @param {object} [opts] - optional modifiers
 * @param {number} [opts.compoundCount] - number of signals in 18mo window
 * @param {boolean} [opts.isReboot] - is this a reboot of a dormant signal?
 * @param {string} [opts.sector] - company sector (for future modifier)
 * @param {string} [opts.country] - company country_code (for future modifier)
 * @returns {object} { score, phase, signal_age_days, peak_window, description }
 */
function computeSignalTimingScore(signalType, signalAgeDays, opts = {}) {
  const { compoundCount = 1, isReboot = false } = opts;

  const calibrated = SLEEP_TIMERS[signalType];
  const t = calibrated?.timer || DEFAULT_TIMER;

  let score = 0;
  let phase = '';

  if (signalAgeDays < t.dormant_until_days) {
    score = 0.15;
    phase = 'too_early';
  } else if (signalAgeDays < t.rising_from_days) {
    score = 0.35;
    phase = 'rising';
  } else if (signalAgeDays < t.peak_start_days) {
    score = 0.6;
    phase = 'approaching_peak';
  } else if (signalAgeDays <= t.peak_end_days) {
    score = 0.85;
    phase = 'peak_window';
  } else if (signalAgeDays <= t.declining_until_days) {
    score = 0.45;
    phase = 'declining';
  } else {
    score = 0.1;
    phase = 'dormant';
  }

  // Compound signal multiplier (more signals = higher confidence)
  if (compoundCount >= 3) score = Math.min(1.0, score * 1.4);
  else if (compoundCount >= 2) score = Math.min(1.0, score * 1.2);

  // Reboot multiplier (dormant signal rebooted = high urgency)
  if (isReboot) score = Math.min(1.0, score * 1.5);

  return {
    score: parseFloat(score.toFixed(2)),
    phase,
    signal_age_days: signalAgeDays,
    peak_window: `${t.peak_start_days}-${t.peak_end_days} days`,
    calibrated: !!calibrated,
    description: getPhaseDescription(phase, signalType, signalAgeDays, t)
  };
}

function getPhaseDescription(phase, signalType, ageDays, timer) {
  const label = signalType.replace(/_/g, ' ');
  switch (phase) {
    case 'too_early':
      return `${label} detected ${ageDays} days ago. Too early for mandate — typical window starts at ${timer.rising_from_days} days.`;
    case 'rising':
      return `${label} signal maturing. Mandate probability rising. Peak window begins at ${timer.peak_start_days} days.`;
    case 'approaching_peak':
      return `${label} signal approaching peak mandate window. Consider proactive outreach.`;
    case 'peak_window':
      return `${label} signal IN PEAK MANDATE WINDOW. Historical data shows highest mandate probability now. Act immediately.`;
    case 'declining':
      return `${label} signal past peak. Mandate probability declining but still elevated. Last window for outreach.`;
    case 'dormant':
      return `${label} signal dormant (${ageDays} days old). Watch for reboot signals.`;
    default:
      return `Signal detected ${ageDays} days ago.`;
  }
}

/**
 * Check for signal reboot when a new signal arrives for a company
 * that has existing dormant signals.
 *
 * @param {object} db - TenantDB instance
 * @param {string} companyId - UUID
 * @param {string} newSignalType - the newly detected signal type
 * @param {string} tenantId - UUID
 * @returns {Promise<Array>} reboot records, empty if no reboots detected
 */
async function checkForReboot(db, companyId, newSignalType, tenantId) {
  const { rows: existingSignals } = await db.query(`
    SELECT signal_type, detected_at,
           EXTRACT(days FROM NOW() - detected_at)::int AS age_days
    FROM signal_events
    WHERE company_id = $1
      AND (tenant_id IS NULL OR tenant_id = $2)
      AND detected_at > NOW() - interval '730 days'
    ORDER BY detected_at DESC
  `, [companyId, tenantId]);

  const reboots = [];
  for (const existing of existingSignals) {
    const calibrated = SLEEP_TIMERS[existing.signal_type];
    const t = calibrated?.timer || DEFAULT_TIMER;

    if (existing.age_days > t.declining_until_days) {
      // This signal was dormant — new signal reboots it
      reboots.push({
        original_type: existing.signal_type,
        original_age_days: existing.age_days,
        reboot_type: newSignalType,
        compound_pattern: `${existing.signal_type} + ${newSignalType}`,
        timing_score: computeSignalTimingScore(newSignalType, 0, {
          compoundCount: existingSignals.length,
          isReboot: true
        })
      });
    }
  }

  return reboots;
}

/**
 * Compute a composite signal lead score for a company, considering
 * all active signals, their timing phases, and compound effects.
 *
 * @param {object} db - TenantDB instance
 * @param {string} companyId - UUID
 * @param {string} tenantId - UUID
 * @returns {Promise<object>} { composite_score, signals, peak_count, phase_summary }
 */
async function computeCompanySignalScore(db, companyId, tenantId) {
  const { rows: signals } = await db.query(`
    SELECT signal_type, confidence_score, detected_at,
           EXTRACT(days FROM NOW() - detected_at)::int AS age_days
    FROM signal_events
    WHERE company_id = $1
      AND (tenant_id IS NULL OR tenant_id = $2)
      AND detected_at > NOW() - interval '730 days'
    ORDER BY detected_at DESC
  `, [companyId, tenantId]);

  if (signals.length === 0) {
    return { composite_score: 0, signals: [], peak_count: 0, phase_summary: 'no_signals' };
  }

  const scored = signals.map(s => ({
    signal_type: s.signal_type,
    confidence: parseFloat(s.confidence_score),
    age_days: s.age_days,
    ...computeSignalTimingScore(s.signal_type, s.age_days, {
      compoundCount: signals.length
    })
  }));

  // Composite: highest individual score, boosted by compound count
  const maxScore = Math.max(...scored.map(s => s.score));
  const peakCount = scored.filter(s => s.phase === 'peak_window').length;
  const compoundBoost = signals.length >= 3 ? 1.3 : signals.length >= 2 ? 1.15 : 1.0;
  const composite = Math.min(1.0, parseFloat((maxScore * compoundBoost).toFixed(2)));

  // Dominant phase
  const phases = scored.map(s => s.phase);
  const dominantPhase = peakCount > 0 ? 'peak_window'
    : phases.includes('approaching_peak') ? 'approaching_peak'
    : phases.includes('rising') ? 'rising'
    : phases.includes('declining') ? 'declining'
    : 'dormant';

  return {
    composite_score: composite,
    signals: scored,
    peak_count: peakCount,
    compound_count: signals.length,
    phase_summary: dominantPhase
  };
}

/**
 * Reload sleep timers from disk (call after re-running calibration).
 */
function reloadTimers() {
  try {
    if (fs.existsSync(timersPath)) {
      SLEEP_TIMERS = JSON.parse(fs.readFileSync(timersPath, 'utf8'));
      return true;
    }
  } catch (e) {
    console.warn('signal_timing: failed to reload sleep_timers.json:', e.message);
  }
  return false;
}

module.exports = {
  computeSignalTimingScore,
  computeCompanySignalScore,
  checkForReboot,
  reloadTimers,
  SLEEP_TIMERS
};
